{
  try {
    latch.await();
  }
 catch (  InterruptedException e) {
    throw new AssertionError("Interrupted",e);
  }
}
