{
  testCallEmpty(db,adminSubject,"CALL dbms.createUser('Craig', '1234', true)",null);
  assertNotNull("User Craig should exist",manager.getUser("Craig"));
  testCallEmpty(db,adminSubject,"CALL dbms.deleteUser('Craig')",null);
  assertNull("User Craig should not exist",manager.getUser("Craig"));
  try {
    testCallEmpty(db,adminSubject,"CALL dbms.deleteUser('Craig')",null);
    fail("Expected exception to be thrown");
  }
 catch (  QueryExecutionException e) {
    assertTrue("Exception should contain 'The user 'Craig' does not exist''",e.getMessage().contains("The user 'Craig' does not exist"));
  }
}
