{
  throw new AssertionError(message,cause);
}
