{
  CompletableFuture<Integer> future=new CompletableFuture<>();
  try {
    future.get(1,MILLISECONDS);
    fail("expected exception not thrown");
  }
 catch (  TimeoutException e) {
  }
}
