{
  try {
    executeCommand("create a,b,a-[:x]->b;");
    executeCommand("start n=node(*) delete n;");
    fail("Should have failed with " + NodeStillHasRelationshipsException.class.getName() + " exception");
  }
 catch (  ShellException e) {
    System.out.println(e);
    assertTrue("Expected notice about cause not found in " + e.getMessage(),e.getMessage().contains(NodeStillHasRelationshipsException.class.getSimpleName()));
  }
}
