{
  if (!reject.test(cause)) {
    exception.set(cause);
  }
}
