{
  try {
    return await();
  }
 catch (  InterruptedException e) {
    throw handleInterrupted(e);
  }
}
