{
  try {
    execute();
    fail("exception expected");
  }
 catch (  IncorrectUsage incorrectUsage) {
    assertThat(incorrectUsage.getMessage(),containsString("to"));
  }
}
