{
  repo.begin(1l);
  try {
    repo.begin(1l);
    fail("Should not have been able to begin.");
  }
 catch (  ConcurrentAccessException e) {
    assertThat(e.getMessage(),equalTo("Cannot begin '1', because an entry with that key already exists."));
  }
}
