{
  Throwable exceptionInOtherThread=join();
  if (exceptionInOtherThread == null) {
    fail("Expected " + exceptionType + " in ThreadedCreate, but no exception was raised");
  }
  assertTrue("Expected " + exceptionType + " in ThreadedCreate, got "+ exceptionInOtherThread.getClass()+ "",exceptionType.isInstance(exceptionInOtherThread));
  assertThat(exceptionInOtherThread.getMessage(),equalTo(msg));
}
