{
  throw new MadeUpException(messageInException,new Exception("The cause of it"));
}
